### PR TITLE
8.5.0

### PR DESCRIPTION
**Pull request by jacobwilliams**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jacobwilliams** [comment]
I don't know if this is the right way to do this, but this MR is same as #6, but with a change to get the tests to build.

**Comment by jacobwilliams** [comment]
Something is still broken.

@awvwgk any ideas?

**Comment by awvwgk** [comment]
The static library is compiled and installed instead of the shared one

**Comment by jacobwilliams** [comment]
https://github.com/jacobwilliams/json-fortran/issues/558

Yep, trying to fix now.

**Comment by jacobwilliams** [comment]
Closing this. Hopefully 8.5.1 will work.

**Pull request closed without merging**
